### PR TITLE
merge work

### PR DESCRIPTION
**Pull request by westshae**

### CODE REVIEW

**Comment by Darkflame72** [comment]
Can you add the VRAM/VSEC/GDSC Groups to the subgroups section

**Comment by Darkflame72** [comment]
Can you use the google calendar for events as it will always be up to date

**Comment by westshae** [comment]
> Can you use the google calendar for events as it will always be up to date

That'll be added in the future

**Comment by Darkflame72** [comment]
> > Can you use the google calendar for events as it will always be up to date
> 
> That'll be added in the future

This needs to be there now as it already exists on the current website and the new one cannot take away functionality

**Pull request closed without merging**
